apiVersion: v1
kind: Service
metadata:
  name: oc-nodejs-basic-service
  labels:
    app: oc-nodejs-basic-service
spec:
  ports:
  - port: 80
    targetPort: 8081
  type: NodePort
  selector:
    app: oc-nodejs-basic-pod
---
apiVersion: v1
kind: Route
metadata:
   name: oc-nodejs-basic-route
spec:
   host: oc-nodejs-basic-service-poc.apps-dev.intra-tpg.ch
   to:
      kind: Service
      name: oc-nodejs-basic-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: oc-nodejs-basic-replica
  labels:
    app: oc-nodejs-basic-replica
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: oc-nodejs-basic-pod
    spec:
      containers:
      - name: oc-nodejs
        image: docker-registry.default.svc:5000/pascal/my-nodejs-example:latest
        ports:
        - containerPort: 8081
---
kind: BuildConfig
apiVersion: v1
metadata:  
    name: my-nodejs-example
annotations:
   description: Defines how to build the application
   template.alpha.openshift.io/wait-for-ready: true
spec:
    source:
       type: Git
       git:
          uri: https://github.com/skal111/oc-nodejs-basic.git

    strategy:  
       type: Docker
    output:  
       to:  
          kind: DockerImage
          name: docker-registry.default.svc:5000/pascal/my-nodejs-example:latest